CREATE TABLE `area` (
`ID_AREA` int(11) NOT NULL AUTO_INCREMENT,
`ID_PARENT_AREA` int(11) NULL DEFAULT NULL,
`NOMBRE` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`DESCRIPCION` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`ESTADO` int(11) NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NOT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_AREA`) ,
INDEX `FK_area_area` (`ID_PARENT_AREA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=7;

CREATE TABLE `cita` (
`ID_CITA` int(11) NOT NULL AUTO_INCREMENT,
`ID_PACIENTE` int(11) NOT NULL,
`ID_DENTISTA` int(11) NOT NULL,
`TIPO_CITA` int(11) NOT NULL,
`FECHA_CITA` date NOT NULL,
`HORA_INICIO` time NOT NULL,
`HORA_FIN` time NOT NULL,
`ESTADO` int(11) NOT NULL,
`NOTA` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_CITA`) ,
INDEX `FK_cita_paciente` (`ID_PACIENTE`),
INDEX `FK_cita_dentista` (`ID_DENTISTA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `detalle_horario` (
`ID_DETALLE_HORARIO` int(11) NOT NULL AUTO_INCREMENT,
`ID_HORARIO` int(11) NOT NULL,
`DIA` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`HORA_INICIO` time NOT NULL,
`HORA_FIN` time NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_DETALLE_HORARIO`) ,
INDEX `FK_horario_detalle_horario` (`ID_HORARIO`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `detalle_medicacion` (
`ID_DETALLE_MEDICACION` int(11) NOT NULL AUTO_INCREMENT,
`ID_MEDICACION` int(11) NOT NULL,
`ID_MEDICAMENTO` int(11) NOT NULL,
`ID_UNIDAD_MEDIDA` int(11) NOT NULL,
`CANTIDAD` float(4,2) NULL DEFAULT NULL,
`DESCRIPCION` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`ACTIVE` int(11) NULL DEFAULT NULL,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_DETALLE_MEDICACION`) ,
INDEX `FK_detalle_medicacion_medicacion` (`ID_MEDICACION`),
INDEX `FK_detalle_medicacion_medicamento` (`ID_MEDICAMENTO`),
INDEX `FK_detalle_medicacion_unidad_medida` (`ID_UNIDAD_MEDIDA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `detalle_odontograma` (
`ID_DETALLE_ODONTOGRAMA` int(11) NOT NULL AUTO_INCREMENT,
`ID_ODONTOGRAMA` int(11) NOT NULL,
`NUMERO_DIENTE` int(11) NOT NULL,
`ID_TRATAMIENTO` int(11) NOT NULL,
`ID_DENTISTA` int(11) NOT NULL,
`DESCRIPCION` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`FECHA_APLICACION` datetime NOT NULL,
`ESTADO` int(11) NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_DETALLE_ODONTOGRAMA`) ,
INDEX `FK_detalle_odontograma_odontograma` (`ID_ODONTOGRAMA`),
INDEX `FK_detalle_odontograma_tratamiento` (`ID_TRATAMIENTO`),
INDEX `FK_detalle_odontograma_dentista` (`ID_DENTISTA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `horario` (
`ID_HORARIO` int(11) NOT NULL AUTO_INCREMENT,
`ID_PERSONAL` int(11) NOT NULL,
`ID_AREA` int(11) NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_HORARIO`) ,
INDEX `FK_horario_area` (`ID_PERSONAL`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `marca` (
`ID_MARCA` int(11) NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`ACTIVE` bit(1) NULL DEFAULT NULL,
`FECHA_REGISTRO` datetime NOT NULL,
`USUARIO_REGISTRO` int(11) NOT NULL,
`FECHA_MODIFICACION` datetime NOT NULL,
`USUARIO_MODIFICACION` int(11) NOT NULL,
PRIMARY KEY (`ID_MARCA`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `medicacion` (
`ID_MEDICACION` int(11) NOT NULL AUTO_INCREMENT,
`ID_DETALLE_ODONTOGRAMA` int(11) NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_MEDICACION`) ,
INDEX `FK_medicacion_detalle_odontograma` (`ID_DETALLE_ODONTOGRAMA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `medicamento` (
`ID_MEDICAMENTO` int(11) NOT NULL AUTO_INCREMENT,
`ID_MARCA` int(11) NOT NULL,
`NOMBRE` varchar(250) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`DESCRIPCION` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`ACTIVE` bit(1) NULL DEFAULT NULL,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_MEDICAMENTO`) ,
INDEX `FK_medicamento_marca` (`ID_MARCA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `odontograma` (
`ID_ODONTOGRAMA` int(11) NOT NULL AUTO_INCREMENT,
`ID_PACIENTE` int(11) NOT NULL,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_ODONTOGRAMA`) ,
INDEX `FK_odontograma_paciente` (`ID_PACIENTE`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `paciente` (
`ID_PACIENTE` int(11) NOT NULL AUTO_INCREMENT,
`ID_PERSONA` int(11) NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_PACIENTE`) ,
INDEX `FK_paciente_persona` (`ID_PERSONA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=5;

CREATE TABLE `persona` (
`ID_PERSONA` int(11) NOT NULL AUTO_INCREMENT,
`TIPO_DOCUMENTO` int(11) NULL DEFAULT NULL,
`NUMERO_DOCUMENTO` varchar(12) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`NOMBRE` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`APELLIDOS` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`DIRECCION` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`EMAIL` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`CELULAR` char(9) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`TELEFONO` char(9) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`FECHA_NACIMIENTO` date NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_PERSONA`) ,
INDEX `fk_persona_tipo` (`TIPO_DOCUMENTO`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=5;

CREATE TABLE `personal` (
`ID_PERSONAL` int(11) NOT NULL AUTO_INCREMENT,
`ID_AREA` int(11) NOT NULL,
`ID_PERSONA` int(11) NOT NULL,
`TIPO_PERSONAL` int(11) NULL DEFAULT NULL,
`FECHA_INGRESO` datetime NOT NULL,
`FECHA_CONTRATO_INICIO` datetime NULL DEFAULT NULL,
`FECHA_CONTRATO_FIN` datetime NULL DEFAULT NULL,
`ESPECILIDAD` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`CARGO` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_PERSONAL`) ,
INDEX `FK_personal_area` (`ID_AREA`),
INDEX `FK_personal_persona` (`ID_PERSONA`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `tipo` (
`ID_TIPO` int(11) NOT NULL AUTO_INCREMENT,
`ID_GRUPO` int(11) NULL DEFAULT NULL,
`NOMBRE` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`VALOR` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`SIGLA` char(5) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_TIPO`) ,
INDEX `FK_tipo_tipo_grupo` (`ID_GRUPO`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=4;

CREATE TABLE `tipo_grupo` (
`ID_GRUPO` int(11) NOT NULL AUTO_INCREMENT,
`NOMBRE_GRUPO` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`DESCRIPCION_GRUPO` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
PRIMARY KEY (`ID_GRUPO`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=4;

CREATE TABLE `tratamiento` (
`ID_TRATAMIENTO` int(11) NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(250) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`DESCRIPCION` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`APLICA_CARA` bit(1) NOT NULL DEFAULT 0,
`APLICA_DIENTE` bit(1) NOT NULL DEFAULT 0,
`PRECIO` double NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_TRATAMIENTO`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `unidad_medida` (
`ID_UNIDAD_MEDIDA` int(11) NOT NULL AUTO_INCREMENT,
`NOMBRE` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
`ACTIVE` bit(1) NULL DEFAULT NULL,
`FECHA_REGISTRO` datetime NOT NULL,
`USUARIO_REGISTRO` int(11) NOT NULL,
`FECHA_MODIFICACION` datetime NOT NULL,
`USUARIO_MODIFICACION` int(11) NOT NULL,
PRIMARY KEY (`ID_UNIDAD_MEDIDA`) 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;

CREATE TABLE `usuario` (
`ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
`ID_PERSONAL` int(11) NOT NULL,
`USERNAME` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`PASSWORD` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`ESTADO` int(11) NOT NULL,
`ACTIVE` bit(1) NOT NULL DEFAULT 0,
`FECHA_CREACION` datetime NULL DEFAULT NULL,
`USUARIO_CREACION` int(11) NULL DEFAULT NULL,
`FECHA_MODIFICACION` datetime NULL DEFAULT NULL,
`USUARIO_MODIFICACION` int(11) NULL DEFAULT NULL,
PRIMARY KEY (`ID_USUARIO`) ,
INDEX `FK_usuario_personal` (`ID_PERSONAL`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_unicode_ci
AUTO_INCREMENT=1;


ALTER TABLE `area` ADD CONSTRAINT `FK_area_area` FOREIGN KEY (`ID_PARENT_AREA`) REFERENCES `area` (`ID_AREA`);
ALTER TABLE `cita` ADD CONSTRAINT `FK_cita_dentista` FOREIGN KEY (`ID_DENTISTA`) REFERENCES `personal` (`ID_PERSONAL`);
ALTER TABLE `cita` ADD CONSTRAINT `FK_cita_paciente` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `paciente` (`ID_PACIENTE`);
ALTER TABLE `detalle_horario` ADD CONSTRAINT `FK_horario_detalle_horario` FOREIGN KEY (`ID_HORARIO`) REFERENCES `horario` (`ID_HORARIO`);
ALTER TABLE `detalle_medicacion` ADD CONSTRAINT `FK_detalle_medicacion_medicacion` FOREIGN KEY (`ID_MEDICACION`) REFERENCES `medicacion` (`ID_MEDICACION`);
ALTER TABLE `detalle_medicacion` ADD CONSTRAINT `FK_detalle_medicacion_medicamento` FOREIGN KEY (`ID_MEDICAMENTO`) REFERENCES `medicamento` (`ID_MEDICAMENTO`);
ALTER TABLE `detalle_medicacion` ADD CONSTRAINT `FK_detalle_medicacion_unidad_medida` FOREIGN KEY (`ID_UNIDAD_MEDIDA`) REFERENCES `unidad_medida` (`ID_UNIDAD_MEDIDA`);
ALTER TABLE `detalle_odontograma` ADD CONSTRAINT `FK_detalle_odontograma_dentista` FOREIGN KEY (`ID_DENTISTA`) REFERENCES `personal` (`ID_PERSONAL`);
ALTER TABLE `detalle_odontograma` ADD CONSTRAINT `FK_detalle_odontograma_odontograma` FOREIGN KEY (`ID_ODONTOGRAMA`) REFERENCES `odontograma` (`ID_ODONTOGRAMA`);
ALTER TABLE `detalle_odontograma` ADD CONSTRAINT `FK_detalle_odontograma_tratamiento` FOREIGN KEY (`ID_TRATAMIENTO`) REFERENCES `tratamiento` (`ID_TRATAMIENTO`);
ALTER TABLE `horario` ADD CONSTRAINT `FK_horario_area` FOREIGN KEY (`ID_PERSONAL`) REFERENCES `area` (`ID_AREA`);
ALTER TABLE `horario` ADD CONSTRAINT `FK_horario_personal` FOREIGN KEY (`ID_PERSONAL`) REFERENCES `personal` (`ID_PERSONAL`);
ALTER TABLE `medicacion` ADD CONSTRAINT `FK_medicacion_detalle_odontograma` FOREIGN KEY (`ID_DETALLE_ODONTOGRAMA`) REFERENCES `detalle_odontograma` (`ID_DETALLE_ODONTOGRAMA`);
ALTER TABLE `medicamento` ADD CONSTRAINT `FK_medicamento_marca` FOREIGN KEY (`ID_MARCA`) REFERENCES `marca` (`ID_MARCA`);
ALTER TABLE `odontograma` ADD CONSTRAINT `FK_odontograma_paciente` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `paciente` (`ID_PACIENTE`);
ALTER TABLE `paciente` ADD CONSTRAINT `FK_paciente_persona` FOREIGN KEY (`ID_PERSONA`) REFERENCES `persona` (`ID_PERSONA`);
ALTER TABLE `persona` ADD CONSTRAINT `fk_persona_tipo` FOREIGN KEY (`TIPO_DOCUMENTO`) REFERENCES `tipo` (`ID_TIPO`);
ALTER TABLE `personal` ADD CONSTRAINT `FK_personal_area` FOREIGN KEY (`ID_AREA`) REFERENCES `area` (`ID_AREA`);
ALTER TABLE `personal` ADD CONSTRAINT `FK_personal_persona` FOREIGN KEY (`ID_PERSONA`) REFERENCES `persona` (`ID_PERSONA`);
ALTER TABLE `tipo` ADD CONSTRAINT `FK_tipo_tipo_grupo` FOREIGN KEY (`ID_GRUPO`) REFERENCES `tipo_grupo` (`ID_GRUPO`);
ALTER TABLE `usuario` ADD CONSTRAINT `FK_usuario_personal` FOREIGN KEY (`ID_PERSONAL`) REFERENCES `personal` (`ID_PERSONAL`);

