<section class="content-header">
    <h1>Gestión de pacientes</h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <div class="form-group">
                <label class="control-label">Nombre o apellidos</label>
                <div class="input-group">
                    <input class="form-control" placeholder="Ingrese nombres o apellidos" type="text" id="txtBuscar" name="txtBuscar"/>
                    <div class="input-group-btn">
                        <button title="Buscar" data-toggle="tooltip" class="btn btn-default btn-flat" id="btn-buscar-paciente"><i class="fa fa-search"></i></button>
                        <button title="Limpiar" data-toggle="tooltip" class="btn btn-default btn-flat" id="btn-limpiar"><i class="fa fa-paint-brush"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-list"></i> Lista de pacientes</h3>
                    <div class="box-tools pull-right">
                    <button class="btn btn-box-tool btn-flat label-success" id="btn-agregar-paciente"><i class="fa fa-plus"></i> AGREGAR</button>
                    </div>
                </div>
                <div class="box-body">
                    <table id="datatable-paciente" class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Número Documento</th>
                                <th>Nombre</th>
                                <th>Apellidos</th>
                                <th>Dirección</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="modal-paciente">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="form-paciente">
                <div class="modal-header">
                    <button data-dismiss="modal" class="close">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="txtidpaciente" name="txtidpaciente" value="0" />
                    <input type="hidden" id="txtidpersona" name="txtidpersona" value="0" />
                    <div class="row">
                        <div class="col-xs-7 col-sm-7 col-md-7">
                            <div class="form-group">
                                <label class="control-label">tipo documento</label>
                                <select id="cbotipodocumento" name="cbotipodocumento" class="form-control">
                                </select>
                            </div>
                        </div>
                        <div class="col-xs-5 col-sm-5 col-md-5">
                            <div class="form-group">
                                <label class="control-label">dni</label>
                                <input type="text" name="txtdni" maxlength="8" id="txtdni" class="form-control" />
                            </div>
                        </div>
                    </div>
                  <div class="form-group">
                    <label class="control-label">Nombre</label>
                    <input type="text" name="txtnombre" id="txtnombre" maxlength="150" class="form-control"/>
                  </div>
                  <div class="form-group">
                    <label class="control-label">Apellidos</label>
                    <input type="text" name="txtapellidos" maxlength="150" id="txtapellidos" class="form-control"/>
                  </div>
                  <div class="form-group">
                    <label class="control-label">Dirección</label>
                    <input type="text" name="txtdireccion" maxlength="1024" id="txtdireccion" class="form-control"/>
                  </div>
                  <div class="row">
                    <div class="col-xs-7 col-sm-7 col-md-7">
                      <div class="form-group">
                        <label class="control-label">Email</label>
                        <input type="email" name="txtemail" maxlength="150" id="txtemail" class="form-control"/>
                      </div>
                    </div>
                    <div class="col-xs-5 col-sm-5 col-md-5">
                      <div class="form-group">
                        <label class="control-label">Fecha nacimiento</label>
                        <input type="text" data-mask maxlength="10" name="txtfechanacimiento" id="txtfechanacimiento" class="form-control"/>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                        <div class="col-xs-7 col-sm-7 col-md-7">
                            <div class="form-group">
                                <label class="control-label">telefono</label>
                                <input type="text" name="txttelefono" minlength="9" maxlength="9" digits="true" id="txttelefono" class="form-control" />
                            </div>
                        </div>
                        <div class="col-xs-5 col-sm-5 col-md-5">
                            <div class="form-group">
                                <label class="control-label">celular</label>
                                <input type="text" name="txtcelular" minlength="9" maxlength="9" digits="true" id="txtcelular" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default btn-flat btn-sm" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-success btn-flat btn-sm" id="btn-guardar-paciente"><i class="fa fa-save"></i> Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
