<section class="content-header">
    <h1>Configuración de tipos</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">GRUPO</span>
                    <select class="form-control" id="cbotipogrupo" name="cbotipogrupo"></select>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <div class="btn-group">
                    <button id='btn-agregar-grupo' title="Agregar Grupo" data-toggle="tooltip" class="btn btn-success btn-flat"><i class="fa fa-plus"></i></button>
                    <button id='btn-editar-grupo' disabled="disabled" title="Editar Grupo" onclick="BasePage.GetGrupo()" data-toggle="tooltip" class="btn btn-info btn-flat"><i class="fa fa-edit"></i></button>
                    <button id='btn-eliminar-grupo' disabled="disabled" title="Eliminar Grupo" onclick="BasePage.DeleteGrupo()" data-toggle="tooltip" class="btn btn-danger btn-flat"><i class="fa fa-remove"></i></button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-list"></i> Lista de tipos</h3>
                    <div class="box-tools pull-right">
                        <button id="btn-agregar-tipo" disabled="disabled" class="btn btn-box-tool btn-flat label-success"><i class="fa fa-plus"></i> AGREGAR</button>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table" id="datatable-tipo">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Sigla</th>
                                <th>Valor</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="modal fade" id="modal-tipo-grupo">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="form-tipo-grupo">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Nuevo Tipo Grupo</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="txtidgrupo" id="txtidgrupo"/>
                    <div class="form-group">
                        <label class="control-label">Nombre</label>
                        <input type="text" required="true" letras="true" maxlength="250" name="txtnombregrupo" id="txtnombregrupo" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Descripción</label>
                        <textarea maxlength="1024" row="5" class="form-control" id="txtdescripciongrupo" name="txtdescripciongrupo"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default btn-flat" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-success btn-flat" id="btn-guardar-grupo" ><i class="fa fa-save"></i> Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-tipo">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="form-tipo">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Nuevo Tipo Grupo</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="txtidtipo" id="txtidtipo"/>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label class="control-label">Nombre</label>
                                <input type="text" required="true" letras="true" maxlength="300" name="txtnombretipo" id="txtnombretipo" class="form-control"/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-8">
                            <div class="form-group">
                                <label class="control-label">Valor</label>
                                <input type="text" maxlength="50" class="form-control" id="txtvalortipo" name="txtvalortipo"/>
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group">
                                <label class="control-label">Sigla</label>
                                <input type="text" maxlength="5" class="form-control" id="txtsiglatipo" name="txtsiglatipo"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default btn-flat" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-success btn-flat" id="btn-guardar-tipo" ><i class="fa fa-save"></i> Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
