<?php
use Application\Model\Entity\Enviroment;
$this->doctype();
$cookie = Enviroment::GetCookieUsuario();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Sistema clinica dental')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/dist/img/diente.png'])
            ->prependStylesheet($this->basePath('dist/css/style.css'))
            ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('plugins/fullcalendar/fullcalendar.print.css'), 'print', true,['id'=>'printStyles'])
            ->prependStylesheet($this->basePath('plugins/fullcalendar/fullcalendar.css'))
            ->prependStylesheet($this->basePath('plugins/select2/select2.min.css'))
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))

            ->prependStylesheet($this->basePath('plugins/bootstrap-notify/animate.css'))
            ->prependStylesheet($this->basePath('plugins/datatables/extensions/Responsive/css/dataTables.responsive.css'))
            ->prependStylesheet($this->basePath('plugins/datatables/dataTables.bootstrap.css'))
            ->prependStylesheet($this->basePath('plugins/datepicker/datepicker3.css'))
            ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.min.css'))
        ?>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <!-- Scripts -->

        <?= $this->headScript()->
            appendFile($this->basePath('plugins/jQuery/jquery-2.2.3.min.js'))->
            //appendFile('https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.js')
            appendFile($this->basePath('plugins/jQueryValidate/jquery.validate.js'))
            ->appendFile($this->basePath('plugins/select2/select2.full.min.js'))
        ?>
    </head>
    <body class="hold-transition skin-blue-light sidebar-mini overlay">
        <div class="wrapper">
            <header class="main-header">

                <a href="<?=$this->basePath('/')?>" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>Del</b>PUE</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Del Pueblo</b> E.I.R.L</span>
                </a>
                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                    <span class="hidden-xs"><?=$cookie['NOMBRE']?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="user-header">
                                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                        <p><?=$cookie['NOMBRE'].' '.$cookie['APELLIDOS']?> <small><?=$cookie['USERNAME']?></small></p>
                                    </li>
                                    <li class="user-body">

                                    </li>
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a class="btn btn-default btn-flat">Citas</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?=$this->url('auth', array('action'=>'logout'));?>" class="btn btn-danger btn-flat"><i class="fa fa-sign-out"></i> Salir</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <aside class="main-sidebar">
                <section class="sidebar">
                    <ul class="sidebar-menu">
                        <li class="header">PANEL DE ADMINISTRACIÓN</li>
                        <li class="treeview" data-controllers="tipo">
                            <a href="#">
                                <i class="fa fa-gear"></i>
                                <span>Configuración</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-right pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?=$this->basePath()?>/tipo"><i class="fa fa-indent"></i> Tipo</a></li>
                                <li><a href="<?=$this->basePath()?>/usuario"><i class="fa fa-users"></i> Usuarios</a></li>
                            </ul>
                        </li>
                        <li class="treeview" data-controllers="area,paciente,tratamiento,personal">
                            <a href="#">
                                <i class="fa fa-gears"></i>
                                <span>Mantenimiento</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-right pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?=$this->basePath()?>/area"><i class="fa fa-check"></i> Áreas</a></li>
                                <li><a href="<?=$this->basePath()?>/personal"><i class="fa fa-child"></i> Personal</a></li>
                                <li><a href="<?=$this->basePath()?>/paciente"><i class="fa fa-user-plus"></i> Pacientes</a></li>
                                <li><a href="<?=$this->basePath()?>/tratamiento"><i class="fa fa-tint"></i> Tratamientos</a></li>
                            </ul>
                        </li>
                        <li class="treeview" data-controllers="odontograma,cita">
                            <a href="#">
                                <i class="fa fa-navicon"></i>
                                <span>Procesos</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?=$this->basePath()?>/odontograma"><i class="fa fa-history"></i> Odontograma</a></li>
                                <li><a href="<?=$this->basePath()?>/cita"><i class="fa fa-group"></i> Citas</a></li>
                            </ul>
                        </li>
                    </ul>
                </section>
            </aside>
            <div class="content-wrapper">
                <?=$this->content?>
            </div>

            <footer class="main-footer">
                <div class="pull-right hidden-xs"><b>Version</b> 2.3.8</div>
                <strong>Copyright © 2014-2016 <a href="http://apps-tnqsoft.azurewebsites.net">TnqSoft</a>.</strong> Todos los derechos reservados.
            </footer>
        </div>
        <?= $this->inlineScript()->
            //appendFile('https://code.jquery.com/ui/1.11.4/jquery-ui.min.js')->
            appendFile($this->basePath('plugins/jQueryUI/jquery-ui.min.js'))->
            appendFile($this->basePath('bootstrap/js/bootstrap.min.js'))->
            appendFile($this->basePath('plugins/knob/jquery.knob.js'))->
            appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js')->
            appendFile($this->basePath('plugins/fullcalendar/fullcalendar.min.js'))->
            appendFile($this->basePath('plugins/fullcalendar/locale/es.js'))->
            appendFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))->
            appendFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))->
            appendFile($this->basePath('plugins/fastclick/fastclick.js'))->
            appendFile($this->basePath('dist/js/app.min.js'))->

            appendFile($this->basePath('plugins/mask/jquery.mask.min.js'))->
            appendFile($this->basePath('plugins/datatables/jquery.datatables.min.js'))->
            appendFile($this->basePath('plugins/datatables/datatables.bootstrap.min.js'))->
            appendFile($this->basePath('plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js'))->
            appendFile($this->basePath('plugins/bootstrapDialog/bootstrap-dialog.min.js'))->
            appendFile($this->basePath('plugins/datepicker/bootstrap-datepicker.js'))->
            appendFile($this->basePath('plugins/bootstrap-notify/bootstrap-notify.min.js'))->

            appendFile($this->basePath('js/pages/'.$this->ControllerName().'.js'))->
            appendFile($this->basePath('js/app.utils.js'))->
            appendFile($this->basePath('js/dashboard.js?controller='.$this->ControllerName()))?>
    </body>
</html>
