<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 20/07/2017
 **/

namespace Application\Model\Entity;


class Medicacion extends Medicamento
{
    var $ID_MEDICACION;
    var $ID_DETALLE_ODONTOGRAMA;
    var $DESCRIPCION_MEDICACION;
    public function exchangeArray(array $data)
    {
        parent::exchangeArray($data); // TODO: Change the autogenerated stub
        $this->ID_MEDICACION = !empty($data['ID_MEDICACION']) ? $data['ID_MEDICACION'] : null;
        $this->ID_DETALLE_ODONTOGRAMA = !empty($data['ID_DETALLE_ODONTOGRAMA']) ? $data['ID_DETALLE_ODONTOGRAMA'] : null;
        $this->DESCRIPCION_MEDICACION = !empty($data['DESCRIPCION_MEDICACION']) ? $data['DESCRIPCION_MEDICACION'] : null;
    }
}