<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 20/07/2017
 **/

namespace Application\Model\Entity;


class Medicamento extends Marca
{
    var $ID_MEDICAMENTO;
    var $NOMBRE;
    var $DESCRIPCION;

    public function exchangeArray(array $data)
    {
        parent::exchangeArray($data); // TODO: Change the autogenerated stub
        $this->ID_MEDICAMENTO = !empty($data['ID_MEDICAMENTO']) ? $data['ID_MEDICAMENTO'] : null;
        $this->NOMBRE = !empty($data['NOMBRE']) ? $data['NOMBRE'] : null;
        $this->DESCRIPCION = !empty($data['DESCRIPCION']) ? $data['DESCRIPCION'] : null;
    }

    public static function getColumnNames()
    {
        return [
            'ID_MEDICAMENTO',
            'NOMBRE',
            'DESCRIPCION'
        ];
    }
}