<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 17/07/2017 - 9:00
 **/
?>
<style>
    .banner
    {
        background: transparent;
    }
</style>
<div id="content-nav">
    <div class="about" id="about">
        <div class="container">
            <h3>Quienes somos</h3>
            <div class="about-grids">
                <div class="col-md-4 about-grid">
                    <img src="<?=$this->basePath('fsite/images/diente.jpg')?>" alt=" " class="img-responsive" />
                    <div class="img-bottom">
                        <p>Dr. Wilfredo Peréz Gonzales</p>
                    </div>
                </div>
                <!--<div class="col-md-4 about-grid">
                    <img src="<//?=$this->basePath('fsite/images/5.jpg')?>" alt=" " class="img-responsive" />
                    <div class="img-bottom">
                        <p>Odont. Martin Cisneros Trujillo</p>
                    </div>
                </div>-->
                <div class="clearfix"> </div>
            </div>
            <div class="about-grids-bottom">
                <div class="col-md-4 about-us">
                    <h4>Sobre Nosotros</h4>
                    <p>Clínica Dental del Pueblo E.I.R.L, un centro especializado en
                        servicios dentales y estéticos. Nuestros profesionales le ofrecerán
                        los tratamientos más adecuados para cuidar su salud oral.</p>
                </div>
                <div class="col-md-4 about-us">
                    <h4>Que hacemos</h4>
                    <p>Todos nuestros tratamientos odontológicos se realizan bajo estrictos
                        estándares de calidad. Visite nuestro centro dental en Chimbote.</p>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>
