<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 17/07/2017 - 9:04
 **/
?>
<style>
    .banner
    {
        background: transparent;
    }
</style>
<div id="content-nav">
    <div class="contact">
        <div class="container">
            <div class="contact-form">
                <h3>Contactanos</h3>
                <div class="col-md-4 contact-form-left">
                    <h4>Informacion de Contacto</h4>
                    <p>Desea comunicarse con nosotros por favor envienos un correo para aclarar sus dudas
                        o saber la informacion de los tratamientos.</p>
                    <h5>Direccion:</h5>
                    <p>Centro Médico Dental del Pueblo E.I.R.L</p>
                    <p>Avenida Av. Jose Galvez Nro. 1240 P.J. el Progreso,</p>
                    <p>Celular: 943621153 </p>
                    <a href="mailto:example@email.com">cmd-delpueblo@gmail.com</a>
                </div>
                <div class="col-md-8 contact-form-right">
                    <h4>Formulario de Contacto</h4>
                    <form>
                        <input type="text" value="Nombre" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
                        <input type="email" value="Correo" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                        <input type="text" value="Telefono" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Telephone';}" required="">
                        <textarea type="text"  onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Mensage...</textarea>
                        <input type="submit" value="Enviar" >
                    </form>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
