<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 17/07/2017 - 9:03
 **/
?>
<style>
    .banner
    {
        background: transparent;
    }
</style>
<div id="content-nav">
    <div class="gallery">
        <div class="container">
            <h3>Galeria</h3>
            <div class="gallery-grids">
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/3.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/3.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/9-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/9.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/5.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/5.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/10-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/10.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/7.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/7.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="gallery-grids">
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/11.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/11.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/8.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/8.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/10-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/10.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/6.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/6.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/9-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/9.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="gallery-grids">
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/3.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/3.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/9-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/9.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/5.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/5.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/10-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/10.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/7.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/7.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="gallery-grids">
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/11.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/11.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/8.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/8.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/10-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/10.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/6.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/6.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="gallery-grid1">
                    <a class="fancybox" href="<?=$this->basePath('fsite/images/9-.jpg')?>" data-fancybox-group="gallery"><img src="<?=$this->basePath('fsite/images/9.jpg')?>" class="img-style row6 img-responsive" alt="" /><span> </span></a>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>
