<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 17/07/2017 - 8:27
 **/
?>

<div id="content-nav">
    <div  id="top" class="callbacks_container wow fadeInUp" data-wow-delay="0.5s">
        <ul class="rslides" id="slider3">
            <li>
                <div class="banner-info">
                    <h1>Nos ocupamos de tus dientes</h1>
                    <p>Clínica Dental Del Pueblo E.I.R.L, un centro especializado en s
                        ervicios dentales y estéticos. Nuestros profesionales le ofrecerán los tratamientos
                        más adecuados para cuidar su salud oral.</p>
                    <!--<a href="single.html" class="hvr-shutter-out-horizontal">Read More</a>-->
                </div>
            </li>
            <li>
                <div class="banner-info">
                    <h1>Comprometidos en dar un buen servicio </h1>
                    <p>en Clínica Dental del Pueblo E.I.R.L nos hemos caracterizado
                        por la seriedad y profesionalidad en todos los tratamientos odontológicos,
                        logrando mejoras en la salud bucal de cada paciente.</p>
                    <!--<a href="single.html" class="hvr-shutter-out-horizontal">Read More</a>-->
                </div>
            </li>
            <li>
                <div class="banner-info">
                    <h1>Contamos con Profesionales de calidad</h1>
                    <p>Nuestra clínica dental cuenta con los mejores dentistas para asegurar la
                        calidad de los tratamientos que tenemos para usted.</p>
                    <!--<a href="single.html" class="hvr-shutter-out-horizontal">Read More</a>-->
                </div>
            </li>
        </ul>
    </div>
</div>
<!-- //banner -->
<!-- banner-bottom -->
<div class="banner-bottom">
    <div class="container">
        <div class="banner-bottom-grids">
            <div class="banner-bottom-grid-left">
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/1.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/1.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/2.jpg')?>" class="b-link-stripe b-animate-go1   swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/2.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/3.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/3.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/4.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/4.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="clearfix"> </div>
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/5.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/5.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/6.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/6.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/7.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/7.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="banner-bottom-grid-left-grid">
                    <a href="<?=$this->basePath('fsite/images/8.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                        <img src="<?=$this->basePath('fsite/images/8.jpg')?>" alt=" " class="img-responsive" />
                    </a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
            <div class="banner-bottom-grid-right">
                <div class="banner-bottom-grid-right-grid">
                    <h3>Contactanos</h3>
                    <p>Tiene alguna duda sobre los servicios. nuestros profesionales
                        especializados en el cuidadodental
                        gustosos le atenderan y solucionaran sus dudas. envienos un mensaje.
                    </p>
                    <form>
                        <input type="text" value="Nombre" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
                        <input type="email" value="Correo" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                        <input type="submit" value="Enviar" >
                    </form>
                </div>
            </div>
            <link rel="stylesheet" href="<?=$this->basePath('fsite/css/swipebox.css')?>">
            <script src="<?=$this->basePath('fsite/js/jquery.swipebox.min.js')?>"></script>
            <script type="text/javascript">
                jQuery(function($) {
                    $(".swipebox").swipebox();
                });
            </script>
        </div>
    </div>
</div>
<!-- //banner-bottom -->
<!-- banner-bottom-video -->
<div class="banner-bottom-video">
    <div class="container">
        <div class="banner-bottom-video-grids">
            <div class="banner-bottom-video-grid-left">
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Historia
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                Clinica Dental del Pueblo E.I.R.L empezo atender en chimbote en el mes de semptiembre del 1997, comenzo con 10 pacientes
                                ahora cuenta con un gran numero de pacientes atendidos y satisfechos por la atencion recibida.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingTwo">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    Objetivo
                                
                                </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                Fidelizar a los pacientes brindandoles una eficiente atencion y servicio.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingThree">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    Mision
                                </a>
                            </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                Brindar un servicio de calidad a pacientes de todas las edades.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingFour">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                    Vision
                                </a>
                            </h4>
                        </div>
                        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                            <div class="panel-body">
                                Ser la empresa lider en el distrito de chimbote en servicios de tratamiento dental.
                            </div>
                        </div>
                    </div>
                    <!--<div class="panel panel-default">
                     <div class="panel-heading" role="tab" id="headingFive">
                       <h4 class="panel-title">
                         <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                           voluptatum deleniti
                         </a>
                       </h4>
                     </div>
                     <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
                        <div class="panel-body">
                         Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
                       </div>
                     </div>
                   </div>-->
                </div>
            </div>
            <div class="banner-bottom-video-grid-right">
                <h4>Ofrecemos una amplia gamas de servicios</h4>
                <div class="banner-bottom-video-grid-rgt">
                    <img src="<?=$this->basePath('fsite/images/7.jpg')?>" alt=" " class="img-responsive" />
                </div>
                <div class="banner-bottom-video-grid-rgt">
                    <ul>
                        <li><a href="#">Blanqueamiento dental</a></li>
                        <li><a href="#">Curaciones dentales</a></li>
                        <li><a href="#">Implantaciones</a></li>
                        <li><a href="#">Estetica dental</a></li>
                        <li><a href="#">ortodoncia</a></li>
                        <li><a href="#">Limpieza dental</a></li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

<div class="view">
    <div class="container">
        <div class="view-left">
            <p><span>DONDE NOS PUEDE ENCONTRAR: </span>Visite nuestras instalaciones en Avenida Jose Galvez 1240 P.J. El Progreso y gustosos
                le atenderemos.
            </p>
        </div>
    </div>
    <div class="map">
        <!--<iframe src="https://www.google.com.pe/maps/place/Panamericana+Nte.+1240,+Chimbote/@-9.0662203,-78.5885375,19z/data=!3m1!4b1!4m5!3m4!1s0x91ab813d45459d03:0x4ec4e7f393a8ae6c!8m2!3d-9.0662216!4d-78.5879903" frameborder="0" style="border:0" allowfullscreen></iframe>-->
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3939.973026749352!2d-78.59017898579054!3d-9.066221593495042!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91ab813d45459d03%3A0x4ec4e7f393a8ae6c!2sPanamericana+Nte.+1240%2C+Chimbote!5e0!3m2!1ses-419!2spe!4v1500785791737" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>
