<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 17/07/2017 - 9:04
 **/

?>
<link href="<?=$this->basePath('fsite/css/bootstrap.css')?>" rel="stylesheet" type="text/css" media="all" />
<link href="<?=$this->basePath('fsite/css/style.css')?>" rel="stylesheet" type="text/css" media="all" />
<link href="<?=$this->basePath('fsite/css/materialize.css')?>" rel="stylesheet" type="text/css" media="all"/>
<link href="<?=$this->basePath('fsite/css/materialize.min.css')?>" rel="stylesheet" type="text/css" media="all"/>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!-- js -->
<script src="<?=$this->basePath('fsite/js/jquery-1.11.1.min.js')?>"></script>
<script type="text/javascript" src="<?=$this->basePath('fsite/js/materialize.js')?>"></script>
<script type="text/javascript" src="<?=$this->basePath('fsite/js/materialize.min.js')?>"></script>
<!-- //js -->
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="<?=$this->basePath('fsite/js/move-top.js')?>"></script>
<script type="text/javascript" src="<?=$this->basePath('fsite/js/easing.js')?>"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $(".scroll").click(function(event){
            event.preventDefault();
            $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
        });
    });
</script>

<style>
    .banner{
        background: transparent;
    }
</style>
<div id="content-nav">
    <div class="contact">
        <div class="container">
            <div class="contact-form">
                <h3>Reservaciones online</h3>
                <!--<div class="col-md-4 contact-form-left">
                    <h4>Informacion de Contacto</h4>
                    <p>Desea comunicarse con nosotros por favor envienos un correo para aclarar sus dudas
                        o saber la informacion de los tratamientos.</p>
                    <h5>Direccion:</h5>
                    <p>Clinica Dental Trujillo</p>
                    <p>Avenida Jose Pardo Nro. 221,</p>
                    <p>Telefono: (43) 32-2553</p>
                    <a href="mailto:example@email.com">flordemariacercadeti@hotmail.com</a>
                </div>-->
                <div class="row">
                    <h4>Formulario Reserva</h4>
                    <form class="col s12">
                        <div class="row">
                            <div class="input-field col s6">
                                <input placeholder="Ingresa tu nombre" id="first_name" type="text" class="validate">
                                <label for="first_name">Nombre</label>
                            </div>
                            <div class="input-field col s6">
                                <input id="last_name" type="text" class="validate" placeholder="Ingresa tu apellido">
                                <label for="last_name">Apellido</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s5">
                                <input placeholder="" id="" type="text" class="validate">
                                <label for="dentista">Dentista</label>
                            </div>
                            <div class="input-field col s3">
                                <a class="waves-effect waves-light btn-large"><i class="material-icons left">search</i>Buscar</a>
                            </div>
                            <div class="input-field col s4">
                                <select>
                                    <option value="">Tipo de Cita</option>
                                    <option value="1">Option 1</option>
                                </select>
                            </div>
                        
                        </div>
                        
                        <div class="row">
                            <div class="input-field col s12">
                                <input type="date" class="datepicker">
                                <label for="fechacita">Ingrese la Fecha de su cita</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <input type="date" class="timepicker" placeholder="ingrese la hora de inicio">
                            </div>
                            <div class="input-field col s6">
                                <input type="date" class="timepicker">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12">
                                <a class="waves-effect waves-light btn-large"><i class="material-icons left">recent_actors</i>Reservar</a>
                            </div>
                        </div>
                </div>
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $().UItoTop({ easingType: 'easeOutQuart' });
    });
</script>
<!-- //here ends scrolling icon -->
<!-- for bootstrap working -->
<script src="<?=$this->basePath('fsite/js/bootstrap.js')?>"> </script>
<!-- //for bootstrap working -->
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
    
    $('select').material_select('destroy');

</script>
<script>
    //calendario
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15 // Creates a dropdown of 15 years to control year
    });
    // hora de inicio y fin
    $('.timepicker').pickatime({
        default: 'now', // Set default time
        fromnow: 0,       // set default time to * milliseconds from now (using with default = 'now')
        twelvehour: true, // Use AM/PM or 24-hour format
        donetext: 'OK', // text for done-button
        cleartext: 'Clear', // text for clear-button
        canceltext: 'Cancel', // Text for cancel-button
        autoclose: false, // automatic close timepicker
        ampmclickable: true, // make AM PM clickable
        aftershow: function(){} //Function for after opening timepicker
    });
</script>
