<?php
/**
 * Apps TunaquiSoft (http://apps-tnqsoft.azurewebsites.net/)
 * -------------------------------------------------------------------------------
 * This file is part of the clident project.
 *
 * @autor @EstevanTn
 * @email tunaqui@outlook.es
 * @copyright Copyright © 2017 - TunaquiSoft
 * @website http://apps-tnqsoft.azurewebsites.net/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 17/07/2017 - 9:03
 **/

?>
<style>
    .banner
    {
        background: transparent;
    }
</style>
<div id="content-nav">
    <div class="services">
        <div class="container">
            <div class="services-overview">
                <h3>Servicios</h3>
                <div class="services-overview-grids">
                    <div class="col-md-4 services-overview-grid">
                        <div class="services-overview-grd">
                            <a href="<?=$this->basePath('fsite/images/esteticadental.jpg')?>" class="b-link-stripe b-animate-go1   swipebox"  title="">
                                <img src="<?=$this->basePath('fsite/images/esteticadental.jpg')?>" alt=" " class="img-responsive" />
                            </a>
                            <div class="services-overview-gd">
                                <h4>Estetica Dental</h4>
                                <p>Nos ocupamos de los problemas de salud dental relacionados
                                    con la armonía estética de la boca, lo que se traduce
                                    básicamente en lograr una sonrisa perfecta,
                                    afeada por diferentes tipos de problemas: Asimetría dental.
                                    Separación entre los dientes anteriores.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 services-overview-grid">
                        <div class="services-overview-grd">
                            <a href="<?=$this->basePath('fsite/images/rehabilitacion.jpg')?>" class="b-link-stripe b-animate-go1   swipebox"  title="">
                                <img src="<?=$this->basePath('fsite/images/rehabilitacion.jpg')?>" alt=" " class="img-responsive" />
                            </a>
                            <div class="services-overview-gd">
                                <h4>Rehabilitacion oral</h4>
                                <p>Nos encargamos de la restauración es decir devolver la función estética y
                                    armonía oral mediante prótesis dentales de perdidas de dientes, grandes
                                    destrucciones o de solucionar problemas estéticos, siempre buscando
                                    una oclusión y función correcta. </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 services-overview-grid">
                        <div class="services-overview-grd">
                            <a href="<?=$this->basePath('fsite/images/odongeneral.jpg')?>" class="b-link-stripe b-animate-go1   swipebox"  title="">
                                <img src="<?=$this->basePath('fsite/images/odongeneral.jpg')?>" alt=" " class="img-responsive" />
                            </a>
                            <div class="services-overview-gd">
                                <h4>Odontologia general</h4>
                                <p>Aplicamos los tratamientos encaminados a solucionar
                                    los problemas primarios que tienen que ver con la boca,
                                    dientes y otras estructuras relacionadas.
                                    En la mayoría de los casos representa el primer
                                    contacto del paciente con el odontólogo.</p>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="services-overview-grids">
                    <div class="col-md-4 services-overview-grid">
                        <div class="services-overview-grd">
                            <a href="<?=$this->basePath('fsite/images/curacion.jpg')?>" class="b-link-stripe b-animate-go1 swipebox"  title="">
                                <img src="<?=$this->basePath('fsite/images/curacion.jpg')?>" alt=" " class="img-responsive" />
                            </a>
                            <div class="services-overview-gd">
                                <h4>Curacion dental</h4>
                                <p>La caries es un proceso peligroso, degenerativo e infeccioso, la cual generalmente destruye estructura dentaria (esmalte y dentina).
                                    Una vez detectada la caries, se procede a su limpieza a través de diferentes técnicas y productos.
                                    La odontología cosmética nos permite el uso de resina para estas curaciones. </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 services-overview-grid">
                        <div class="services-overview-grd">
                            <a href="<?=$this->basePath('fsite/images/imdentales.jpg')?>" class="b-link-stripe b-animate-go1   swipebox"  title="">
                                <img src="<?=$this->basePath('fsite/images/imdentales.jpg')?>" alt=" " class="img-responsive" />
                            </a>
                            <div class="services-overview-gd">
                                <h4>Implantes</h4>
                                <p>Los implantes son raíces dentales artificiales utilizadas
                                    para remplazar dientes perdidos. Los implantes están hechos
                                    de materiales biocompatibles como el titanio que pueden
                                    ser aceptados por el cuerpo humano. Los implantes son
                                    colocados en el hueso donde los dientes están ausentes.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 services-overview-grid">
                        <div class="services-overview-grd">
                            <a href="<?=$this->basePath('fsite/images/ortodoncia.jpg')?>" class="b-link-stripe b-animate-go1   swipebox"  title="">
                                <img src="<?=$this->basePath('fsite/images/ortodoncia.jpg')?>" alt=" " class="img-responsive" />
                            </a>
                            <div class="services-overview-gd">
                                <h4>Ortodoncia</h4>
                                <p> Corrección de los dientes y huesos posicionados
                                    incorrectamente. Los dientes en mala posición y los
                                    que no muerden correctamente unos contra otro
                                    son difíciles de mantener limpios, corren
                                    riesgos de pérdida precoz debido a caries y enfermedades periodontale que puede
                                    generar dolores de cabeza.</p>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
            <link rel="stylesheet" href="<?=$this->basePath('fsite/css/swipebox.css')?>">
            <!--<script src="<?=$this->basePath('fsite/js/jquery.swipebox.min.js')?>"></script>
            <script type="text/javascript">
                jQuery(function($) {
                    $(".swipebox").swipebox();
                });
            </script>-->
        </div>
    </div>
</div>
