<link rel="stylesheet" href="<?=$this->basePath()?>/js/odontograma/css/jquery-ui-1.8.17.custom.css">
<link rel="stylesheet" href="<?=$this->basePath()?>/js/odontograma/css/jquery.svg.css">
<link rel="stylesheet" href="<?=$this->basePath()?>/js/odontograma/css/odontograma.css">
<script src="<?=$this->basePath()?>/js/odontograma/js/modernizr-2.0.6.min.js"></script>

<div class="overlay" id="container-odontograma">
    <section class="content-header">
        <h1>Control de odontogramas</h1>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-solid box-default">
                    <div class="box-body">
                        <div class="input-group">
                            <span class="input-group-addon">PACIENTE</span>
                            <select id="cbolstpacientes" class="form-control select2">
                            </select>
                            <div class="input-group-btn">
                                <button id="btn-mostrar-odontograma" type="button" class="btn btn-default bg-teal"><i class="fa fa-eye"></i> Ver odontograma</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" id="box-persona">
            <div class="col-xs-12 col-sm-4">
                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-user"></i> Información del paciente</h3>
                    </div>
                    <div class="box-body" style="min-height: 270px;">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12">
                                <div class="form-group">
                                    <label class="control-label">N° Documento</label>
                                    <input class="form-control text-center" id="txtnumerodocumento" readonly="readonly" />
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12">
                                <div class="form-group">
                                    <label class="control-label">Nombre y Apellidos</label>
                                    <input class="form-control text-center" readonly="true" id="txtnombreapellidos" />
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6">
                                <div class="form-group">
                                    <label class="control-label">Código Odontograma</label>
                                    <input class="form-control text-center" name="txtcodigoodontograma" id="txtcodigoodontograma" readonly="readonly" />
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6">
                                <div class="form-group">
                                    <label class="control-label">Código Paciente</label>
                                    <input class="form-control text-center" id="txtcodigopaciente" readonly="readonly" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8">
                <div class="box box-widget box-success" >
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-object-group"></i> Odontograma</h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <div id="odontograma-wrapper">
                                    <div id="odontograma"></div>
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-success">
                    <div class="box-header">
                        <h3 class="box-title">Historial de Odontograma</h3>
                    </div>
                    <div class="box-body no-padding">
                        <table class="table table-striped table-hover" id="datatable-detalle-odontograma">
                            <thead>
                            <tr>
                                <th>DIENTE</th>
                                <th>CARA</th>
                                <th>TRATAMIENTO</th>
                                <th>DESCRIPCIÓN</th>
                                <th>FECHA</th>
                                <th>ACCIONES</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="modal-detalle-odontograma">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="" id="form-detalle-odontograma">
                    <div class="modal-header">
                        <button data-dismiss="modal" class="close">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="txtiddetalleodontograma" id="txtiddetalleodontograma">
                        <div class="row">
                            <div class="col-md-4 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label">Diente</label>
                                    <input readonly="readonly" type="text" class="form-control" id="txtnrodetalle" name="txtnrodetalle"/>
                                </div>
                            </div>
                            <div class="col-md-2 col-xs-12">
                                <div class="form-group" id="diente-draw-wrapper">
                                    <div id="diente-draw"></div>
                                </div>
                            </div>
                            <div class="col-md-6 col-xs-12">
                                <div class="form-group">
                                    <label class="control-label">Cara</label>
                                    <select required="required" id="cbocaradetalle" name="cbocaradetalle" class="form-control">
                                        <option value=""><< SELECCIONE >></option>
                                        <option value="I">Inferior</option>
                                        <option value="S">Superior</option>
                                        <option value="D">Derecho</option>
                                        <option value="Z">Izquierdo</option>
                                        <option value="C">Centro</option>
                                        <option value="X">Completo</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label class="control-label">Tratamiento</label>
                                    <select class="form-control" id="cbotratamiento" name="cbotratamiento" min="1"/>
                                        
                                    <select>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label class="control-label">Dentista</label>
                                    <input type="text" class="form-control" id="txtdentistadetalle" name="txtdentistadetalle" readonly="readonly" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="control-label">Descripción</label>
                                    <textarea required="required" class="form-control" row="5" id="txtdescripciondetalle" name="txtdescripciondetalle"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="box box-widget">
                                    <div class="box-header">
                                        <div class="box-title">Detalle de Medicación</div>
                                        <div class="box-tools pull-right">
                                            <button type="button" class="btn btn-box-tool label-success" id="btnagregar-medicacion"><i class="fa fa-plus"></i> Agregar</button>
                                        </div>
                                    </div>
                                    <div class="box-body">
                                        <table class="table" id="datatable-medicacion">
                                            <thead>
                                            <tr>
                                                <th>Medicamento</th>
                                                <th>Marca</th>
                                                <th>Descripción</th>
                                                <th>Acciones</th>
                                            </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn btn-default">Cancelar</button>
                        <button class="btn btn-success" id="btnGuardarDetalleOdontograma"><i class="fa fa-save"></i> Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-medicacion">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="form-medicacion">
                    <div class="modal-header">
                        <button data-dismiss="modal" type="button" class="close">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" id="txtidmedicamento" name="txtidmedicamento" />
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label class="control-label">Medicamento</label>
                                    <select class="form-control" min="1" name="cbomedicamento" id="cbomedicamento"></select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label>Descripción de Medicación</label>
                                    <textarea class="form-control" name="txtdescripcionmedicacion" id="txtdescripcionmedicacion"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn btn-default">Cancelar</button>
                        <button id="btnguardar-medicacion" class="btn btn-success"><i class="fa fa-save"></i> Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!--<script src="<?=$this->basePath()?>/js/odontograma/js/jquery-1.7.1.min.js"></script>-->
<script src="<?=$this->basePath()?>/js/odontograma/js/plugins.js"></script>
<!--<script src="<?=$this->basePath()?>/js/odontograma/js/jquery-ui-1.8.17.custom.min.js"></script>-->
<script src="<?=$this->basePath()?>/js/odontograma/js/jquery.tmpl.js"></script>
<script src="<?=$this->basePath()?>/js/odontograma/js/knockout-2.0.0.js"></script>
<script src="<?=$this->basePath()?>/js/odontograma/js/jquery.svg.min.js"></script>  
<script src="<?=$this->basePath()?>/js/odontograma/js/jquery.svggraph.min.js"></script>  
<script src="<?=$this->basePath()?>/js/odontograma/js/odontograma.TnqSoft.js"></script>