<section class="content">
    <div class="jumbotron">
        <h1>Sistema de Control de <span class="zf-green">Citas y Odontogramas</span></h1>

        <p>
            Esta applicacion esta creada para el control de citas medicas y odontogramas de los pacientes de la clinica
            dental Trujillo, dentro de la localidad de chimbote.
        </p>

        <p>
        
        </p>
    </div>
</section>